<?php
/**
 * Sake
 *
 * @link      http://github.com/sandrokeil/Z-Ray-Doctrine2 for the canonical source repository
 * @copyright Copyright (c) 2015 Sandro Keil
 * @license   http://github.com/sandrokeil/Z-Ray-Doctrine2/blob/master/LICENSE.txt New BSD License
 */

$tableParamsDoctrineCache = array(
    'tableId' => 'table-doctrine-cache',
    'tableWidth' => '4',
);
?>
<p style="padding:5px 10px">
    Displays information about
    <a href="http://doctrine-orm.readthedocs.org/en/latest/reference/caching.html" target="_blank" title="Doctrine 2 cache documentation">Doctrine 2 caches</a>.
</p>
<?= $this->zrayTable($tableParamsDoctrineCache); ?>

<script type="text/javascript">
    (function() {
        var storage = zray.getStorage( 'doctrineCache' );

        // create main table
        var maintable = zray.createTable( storage, jQuery( '#<?php echo $tableParamsDoctrineCache['tableId']; ?>' ) );
        maintable.setColumns( [
            {
                "label": "Cache type",
                "propertyName": "name",
                "sortable": true,
                "width": '20%',
                "tooltip": "Doctrine 2 cache type",
                "getHtml": function( value, record ) {
                    return value;
                }
            },
            {
                "label": "Status",
                "propertyName": "status",
                "sortable": true,
                "width": '80%',
                "tooltip": "Which cache driver is used",
                "getHtml": function( value, record ) {
                    return value;
                }
            }
        ] );
        // create main table - end

        // create pager and search
        zray.createPager( storage, jQuery( '#<?php echo $params['pagerId']; ?>' ) );
        zray.createSearch( storage, jQuery( '#<?php echo $params['searchId']; ?>' ), maintable );

        zray.registerDataHandler( 'doctrine2', 'cache', function( extensionData, requestData ) {
            storage.setData( extensionData );
        } );
    })();
</script>
