<?php
/**
 * Sake
 *
 * @link      http://github.com/sandrokeil/Z-Ray-Doctrine2 for the canonical source repository
 * @copyright Copyright (c) 2015 Sandro Keil
 * @license   http://github.com/sandrokeil/Z-Ray-Doctrine2/blob/master/LICENSE.txt New BSD License
 */

$tableParamsDoctrineQueries = array(
    'tableId' => 'table-doctrine-queries',
    'tableWidth' => '4'
);
?>

<p style="padding:5px 10px">This is a list of executed Doctrine 2 queries.</p>
<?= $this->zrayTable($tableParamsDoctrineQueries); ?>

<script type="text/javascript">
    (function() {
        var storage = zray.getStorage( 'doctrineQueries' );

        // create main table
        var maintable = zray.createTable( storage, jQuery( '#<?php echo $tableParamsDoctrineQueries['tableId']; ?>' ) );
        maintable.setColumns( [
            {
                "label": "Query",
                "propertyName": "query",
                "sortable": true,
                "width": '60%',
                "tooltip": "The executed query",
                "getHtml": function( value, record ) {
                    return value;
                }
            },
            {
                "label": "Number",
                "propertyName": "number",
                "sortable": true,
                "width": '20%',
                "tooltip": "The number of executions e.g. with different parameters",
                "getHtml": function( value, record ) {
                    return value;
                }
            },
            {
                "label": "Cached",
                "propertyName": "cached",
                "sortable": true,
                "width": '20%',
                "tooltip": "The number of cached queries",
                "getHtml": function( value, record ) {
                    return value;
                }
            }
        ] );
        // create main table - end

        // create pager and search
        zray.createPager( storage, jQuery( '#<?php echo $params['pagerId']; ?>' ) );
        zray.createSearch( storage, jQuery( '#<?php echo $params['searchId']; ?>' ), maintable );

        zray.registerDataHandler( 'doctrine2', 'queries', function( extensionData, requestData ) {
            storage.setData( extensionData );
        } );
    })();
</script>
